version: '2.4'
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment: 
      WATCHTOWER_SCHEDULE: "0 0 1 * * *" 
      WATCHTOWER_CLEANUP: "true"   
    restart: unless-stopped
